### ISSUE TITLE
Add `bounding_box` field to the `CustomVectorDataset`

### ISSUE THREAD

**Issue by russelldj** [open-forest-observatory/tree-detection-framework#25]
Currently we only have the polygon `shapes` returned. It would be useful to also returned the axis-aligned bounding box. This will reduce the computation required in downstream steps for approaches that only require bounding boxes. This information should be another attribute of the returned dictionary and in a tabular format. It can be in any standard format (ex. top, left, width, height or top, left, bottom, right) but the convention should be clearly documented.

**Comment by amrithasp02** [comment]
Completed in pull request #31
