### ISSUE TITLE
Support loading vector data as labels

### ISSUE THREAD

**Issue by russelldj** [open-forest-observatory/tree-detection-framework#4]
Currently we support loading raster data and chipping it up into tiles. Most of our labels for ML tasks are represented as geospatial vector data. We should support loading this data as well. I'll defer to you, but my initial thought of how to approach it is the following:
- Provide an additional argument for vector data labels
- Create a [VectorData](https://torchgeo.readthedocs.io/en/stable/api/datasets.html#torchgeo.datasets.VectorDataset) dataset for this. There may need to be some additional keywords to tell it how to use the data, such as an attribute to read from. 
- Create an [IntersectionData](https://torchgeo.readthedocs.io/en/stable/api/datasets.html#torchgeo.datasets.IntersectionDataset) to combine the imagery and the labels. You may have to ensure that the CRS and resolution of this dataset is as expected.
- Draw samples from this dataset. I'm not sure exactly what format they'll be in, so this will need to be explored. But we will eventually want to be able to save and visualize labels for each chip in some format.

**Comment by amrithasp02** [comment]
Was completed in PR #10
