### ISSUE TITLE
Include progress bar or progress messages in Detector.predict

### ISSUE THREAD

**Issue by youngdjn** [open-forest-observatory/tree-detection-framework#42]
Some predictions can take a long time and it can be unclear when (or whether) they will finish. To help with this, it would be nice to include some sort of progress reporting in `Detector.predict`, such as `Performing prediction: 4% complete (chip 2 of 50 in image 1 of 1)`.

**Comment by russelldj** [comment]
The [tqdm](https://pypi.org/project/tqdm/) library is a nice way to do this. The `desc` attribute when creating a progress bar allows you to add descriptive text.
