### ISSUE TITLE
Determine whether to continue accepting an input image *folder* or switch to input *file*

### ISSUE THREAD

**Issue by youngdjn** [open-forest-observatory/tree-detection-framework#47]
It is unclear why the TorchGeo RasterDataset constructor expects a path to a folder of images instead of a single image. How does it handle overlapping rasters? For example, does it provide a tile from each raster? Can tiles consist of data from two rasters? Are they merged or blended?

A case where supplying a folder of rasters may be valuable to us is if we have a dataset consisting of multiple flight polygons flown with different batteries that neighbor each other. We might want to process each battery with photogrammetry individually but merge the predictions together.

If we think it makes sense to accept a single raster instead, we could probably tweak the torchgeo code to accept that instead or have a step where the raster is symlinked into a temporary folder that contains only that one file.

**Comment by russelldj** [comment]
It looks like torchgeo is flexible and can except a path to a single raster instead of a folder of rasters. We still don't know exactly how a folder with multiple overlapping files is handled.
