### ISSUE TITLE
Move chipping script from sandbox to main module

### ISSUE THREAD

**Issue by russelldj** [open-forest-observatory/tree-detection-framework#5]
The content from the chipping script should be factored out into a couple places in the code. My initial suggestion would be the following
- Move the dataloader and sampling code into the `preprocessing` folder
- Move functions that might be reusable into the `utils` folder
- Create a new script in `entrypoints` that performs the same functionality. One option would be to have only the argparse functionality in this script and just call a function defined elsewhere, such as in `preprocessing`. Alternatively, if you think some logic is only specific to the saving/visualizing workflow, you can implement that portion of the logic in this file. But we should try to have the majority of the reusable functionality, such as creating a data loader, in `preprocessing`.

**Comment by amrithasp02** [comment]
Done in PR #16
