### ISSUE TITLE
Create a UML diagram of the proposed structure of this project

### ISSUE THREAD

**Issue by russelldj** [open-forest-observatory/tree-detection-framework#8]
We have a general outline of the structure of this project in an internal doc [here](https://docs.google.com/document/d/12B3Skydst4EqZRtJBVcqHN9-yHwkMAhCks0AFpIQ1Bo/edit?usp=sharing). It would be useful to translate this into a UML diagram that defines some of the major attributes of the system. At first glance, focusing on a UML `class` diagram seems most helpful, but other types could be useful.

**Comment by amrithasp02** [comment]
[Class Diagram (in-progress)](https://drive.google.com/file/d/1i_ngKzNxiein1r6CT-P_feDRoCiJGl4I/view?usp=sharing)
